---
name: Testing

env:
  DOCKER_HUB_ID: ${{ secrets.OHAI_DOCKER_HUB_ID }}
  DOCKER_HUB_PASSWORD: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}
  GO_VERSION: '1.16.1'

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - README.md
jobs:
  unit-test-linux:
    name: Linux unit tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Running unit tests
        run: make ci/test

  test-go-linux:
    name: Linux unit tests for Go
    runs-on: ubuntu-20.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Running unit tests
        run: make go-test

  check-gen-code:
    name: Checking generated code
    runs-on: ubuntu-20.04

    steps:
      - name: Checking generated code
        run: make ci/check-gen-code

  test-build:
    name: Test jar compilation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_ID }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      - name: Build noarch
        run: make ci/build

